"""Add User

Revision ID: 3392362eadbf
Revises: e1e832119335
Create Date: 2026-02-20 14:18:46.408972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3392362eadbf'
down_revision = 'e1e832119335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
